---
fixtures:
  forge_modules:
    # Core Dependencies
    archive: "puppet/archive"
    healthcheck: "puppet/healthcheck"
    kmod: "camptocamp/kmod"
    selinux: "puppet/selinux"
    stdlib: "puppetlabs/stdlib"
    # Fixture-specific Dependencies
    yumrepo_core: "puppetlabs/yumrepo_core"
    mount_core: "puppetlabs/mount_core"
    augeasproviders_core: "herculesteam/augeasproviders_core"
    augeasproviders_sysctl: "herculesteam/augeasproviders_sysctl"
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
